#########################################################
# This Vagrantfile defines the configuration that will  #
# be used by the virtual machine module (VMM) to        #
# demonstrate the provision of the MetaWorks Pipeline   # 
# Computational Environment through the implementation  #
#  based on the Environment Code-First Framework        #
# #######################################################
Vagrant.configure("2") do |config|
  
  # Define the virtual machine image
  # Ubuntu 18.04 64 bits
  config.vm.box = "bento/ubuntu-18.04"

  # Define the hostname and the network
  config.vm.define :chd_ecf_vmm do |chd_config|
    chd_config.vm.hostname = "chd-ecf-vmm"
    chd_config.vm.network "private_network", type "dhcp"

    # Define the Ansible configuration
    chd_config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "chd_ecf.yml"
        ansible.verbose = "vvv"
    end
	
	# Define the provider (virtualbox), quantity of memory,
	# and how many CPUs will be used on the VM
	config.vm.provider "virtualbox" do |domain|
		domain.memory = 8192
		domain.cpus = 1
	end
  end
end
